#pragma once

#define PROJ_BUTTONS_POLLING_ONLY
#define PROJ_HIGH_RAM HIGH_RAM_MUSIC
#define PROJ_AUD_FREQ 16000

#define PROJ_SCREENMODE MODE15
#define PROJ_PERSISTENCE true
#define PROJ_FPS 60

#define GAME_MODE_EASY_BOMB_COUNT       10
#define GAME_MODE_MEDIUM_BOMB_COUNT     40
#define GAME_MODE_HARD_BOMB_COUNT       99
